### ISSUE TITLE
Use of signed char fails on ARM architectures

### ISSUE THREAD

**Issue by girgink** [pygeos/pygeos#291]
Hi,

On NVIDIA Jetson AGX (ARMv8) I do a fresh install of pygeos using Docker:

```
docker run -it --user root --rm arm64v8/ubuntu:20.04

apt-get update
apt-get install -y python3-dev python3-pip libgeos-dev
pip3 install --no-cache-dir cython 
pip3 install --no-cache-dir numpy
pip3 install --no-cache-dir --no-build-isolation pygeos
```

The following [example given in the documentation](https://pygeos.readthedocs.io/en/latest/set_operations.html) for `union_all()` method results in TypeError: 

```
import pygeos

line_1 = pygeos.Geometry("LINESTRING(0 0, 2 2)")
line_2 = pygeos.Geometry("LINESTRING(2 2, 3 3)")
pygeos.union_all([line_1, line_2])
```

Error message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pygeos/decorators.py", line 55, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pygeos/set_operations.py", line 353, in union_all
    collections = lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
TypeError: One of the Geometry inputs is of incorrect geometry type.
```

**Comment by girgink** [comment]
Tests also fail with the same error if I install from the repository:

```
apt-get install git
pip3 install --no-cache-dir pytest
cd /tmp
git clone https://github.com/pygeos/pygeos.git
cd pygeos
pip3 install -e .[test] --no-build-isolation
pytest pygeos
```

Output:

```
=============================================== test session starts ================================================
platform linux -- Python 3.8.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /tmp/pygeos
collected 18 items / 10 errors / 8 selected

====================================================== ERRORS ======================================================
________________________________ ERROR collecting pygeos/test/test_constructive.py _________________________________
pygeos/test/test_constructive.py:7: in <module>
    from .common import (
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
_________________________________ ERROR collecting pygeos/test/test_coordinates.py _________________________________
pygeos/test/test_coordinates.py:7: in <module>
    from .common import empty
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
__________________________________ ERROR collecting pygeos/test/test_creation.py ___________________________________
pygeos/test/test_creation.py:5: in <module>
    from .common import (
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
__________________________________ ERROR collecting pygeos/test/test_geometry.py ___________________________________
pygeos/test/test_geometry.py:6: in <module>
    from .common import point
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
_____________________________________ ERROR collecting pygeos/test/test_io.py ______________________________________
pygeos/test/test_io.py:8: in <module>
    from .common import all_types, point, empty_point, point_z
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
___________________________________ ERROR collecting pygeos/test/test_linear.py ____________________________________
pygeos/test/test_linear.py:5: in <module>
    from .common import empty_point
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
_________________________________ ERROR collecting pygeos/test/test_measurement.py _________________________________
pygeos/test/test_measurement.py:6: in <module>
    from .common import point_polygon_testdata
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
_________________________________ ERROR collecting pygeos/test/test_predicates.py __________________________________
pygeos/test/test_predicates.py:6: in <module>
    from .common import point, all_types, line_string, polygon, geometry_collection, empty
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
_______________________________ ERROR collecting pygeos/test/test_set_operations.py ________________________________
pygeos/test/test_set_operations.py:7: in <module>
    from .common import point, all_types, polygon, multi_polygon
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
___________________________________ ERROR collecting pygeos/test/test_strtree.py ___________________________________
pygeos/test/test_strtree.py:7: in <module>
    from .common import (
pygeos/test/common.py:22: in <module>
    geometry_collection = pygeos.geometrycollections(
pygeos/creation.py:174: in geometrycollections
    return lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
E   TypeError: One of the Geometry inputs is of incorrect geometry type.
============================================= short test summary info ==============================================
ERROR pygeos/test/test_constructive.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
ERROR pygeos/test/test_coordinates.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
ERROR pygeos/test/test_creation.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
ERROR pygeos/test/test_geometry.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
ERROR pygeos/test/test_io.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
ERROR pygeos/test/test_linear.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
ERROR pygeos/test/test_measurement.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
ERROR pygeos/test/test_predicates.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
ERROR pygeos/test/test_set_operations.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
ERROR pygeos/test/test_strtree.py - TypeError: One of the Geometry inputs is of incorrect geometry type.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 10 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================ 10 errors in 1.37s ================================================
```

**Comment by brendan-ward** [comment]
Thanks for the error report.

The operations execute successfully on x86_64 architectures.  I don't believe we have performed any test on ARM architectures yet.  This could be coming from `GEOS`; I do not see that it is being [tested against ARM architectures](https://github.com/libgeos/geos/blob/3.9/.github/workflows/ci.yml) either.

For the time being, I'd recommend using x86_64 architectures.

**Comment by girgink** [comment]
Unfortunately it is not possible, we are running a research platform based on ARM units.

Are you sure that it is not related to PyGeos C library, more specifically `create_collection_func()` function? The error message seems to be PyGeos error message, not GEOS.

**Comment by girgink** [comment]
I can confirm that GEOS passes its tests:

```
docker run -it --user root --rm arm64v8/ubuntu:20.04

apt-get update
apt-get install -y g++ cmake wget
cd /tmp
wget -nv http://download.osgeo.org/geos/geos-3.9.0.tar.bz2 -O - | tar xj
cd geos-3.9.0
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j8
ctest

100% tests passed, 0 tests failed out of 294

make install

(install PyGeos as previously, without apt install libgeos-dev)

python3

Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygeos
>>>
>>> line_1 = pygeos.Geometry("LINESTRING(0 0, 2 2)")
>>> line_2 = pygeos.Geometry("LINESTRING(2 2, 3 3)")
>>> pygeos.union_all([line_1, line_2])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pygeos/decorators.py", line 55, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pygeos/set_operations.py", line 353, in union_all
    collections = lib.create_collection(geometries, GeometryType.GEOMETRYCOLLECTION)
TypeError: One of the Geometry inputs is of incorrect geometry type.

```

As a side note, GEOS 3.8.1 fails with 4 tests:

```
98% tests passed, 4 tests failed out of 259

Total Test time (real) =  11.53 sec

The following tests FAILED:
         68 - unit-capi-GEOSVoronoiDiagram (Failed)
        112 - unit-linearref-LengthIndexedLine (Failed)
        158 - general-TestCentroid (Failed)
        203 - issue-issue-geos-350 (Failed)
```

**Comment by brendan-ward** [comment]
Thanks for additional testing and following up on this.  I'm not seeing anything obvious in `create_collection` that should be architecture dependent, but I think this error originates from a call to get the GEOS geometry from the Python object holding a pointer to it.

Would you mind trying `pygeos.get_type_id(line_1)`?  This would fail if there is an issue with how we're getting the GEOS geometry from Python object.

Many of the test cases create collections for testing, so the failures on `create_collection` may be masking underlying issues in the tests.

Unfortunately, I don't see an easy way to run an ARM container on my machine (MacOS) so unless other devs can help here, I'm not able to dig in further without getting a CI test machine running on ARM.

**Comment by girgink** [comment]
Sure, here is the result:

```
>>> pygeos.get_type_id(line_1)
1
```

It looks like somehow `type` gets an invalid value inside the `BINARY_SINGLE_COREDIM_LOOP_OUTER` loop.

If you don't need root access I can provide access to our platform. It is based on JupyterHub and provides terminal (bash) access.

**Comment by brendan-ward** [comment]
Got an ARM docker container working locally and was able to isolate this specific issue.  We're using a signed `char` value here: https://github.com/pygeos/pygeos/blob/0.9/src/ufuncs.c#L1980
assigned to -1 under certain cases.

It looks like `char` is typically signed on x86_64, but unsigned on ARM ([ref](https://www.linuxtopia.org/online_books/an_introduction_to_gcc/gccintro_71.html))

Since we're using -1 as a sentinel value, we can probably select another appropriate value instead.

Not sure yet where else this error may occur.

**Comment by brendan-ward** [comment]
All other tests pass for me in the ARM container locally.

**Comment by jorisvandenbossche** [comment]
Thanks @girgink and @brendan-ward !

It would be good to actually test on ARM. @brendan-ward do you have an idea if we can run it (eg with docker) on github actions? I know that in pandas this is still one of the things we use Travis for to run on arm64 (if we eg only do this nightly, we might keep it within the free limits) 
Something else I thought about: conda-forge supports building packages for arm architectures, it might be interesting to enabled that for geos/pygeos (numpy already has such packages)

**Comment by girgink** [comment]
Thanks a lot @brendan-ward!

**Comment by brendan-ward** [comment]
Agreed that it would be good to test on ARM.  Also agreed that building for ARM using conda is a good idea.

I think github-hosted ARM action runners are [coming](https://github.com/github/roadmap/issues/95) this year, but not yet generally available.  I _think_ it is possible to do at least some testing of ARM in emulation mode on an existing x86_64 host, though it is pretty slow.

It looks like it is possible to use an action like [run-on-arch-action](https://github.com/uraimo/run-on-arch-action) to run in emulation mode on existing runners (if I follow how it works correctly).

I just pushed the `Dockerfile` I used for testing to the PR as well, for local testing & troubleshooting.

**Comment by jorisvandenbossche** [comment]
The Arm64 Travis build is passing now on master (and the ppc64le build as well). 

@girgink would it be useful to have a release with this fix, or are you OK with installing the master branch for now?

The s390x build is still failing after #293, see https://travis-ci.com/github/pygeos/pygeos/jobs/481129309 (from looking at the errors, it might also be a problem that GEOS itself doesn't fully run correctly on s390x. There seems to be a problem with WKB conversion)

**Comment by girgink** [comment]
@jorisvandenbossche It is perfectly fine to install the master. Thanks for asking!
