### ISSUE TITLE
Spatial join returns incorrect results with Shapely 1.8, due to shapely_compatible optimistically set to True

### ISSUE THREAD

**Issue by nicolaslegrand91** [pygeos/pygeos#424]
#### Code Sample, a copy-pastable example

```python
import geopandas as gpd
from shapely import wkt

# Define 2 geometries
point = wkt.loads('POINT (-3.61104 54.12069)')
polygon = wkt.loads('''
    Polygon ((-3.63156666666667 54.1267166666667,-3.53435 54.0763833333333,-3.5634 54.0383333333333,
    -3.58396666666667 54.0467,-3.60175 54.0521333333333,-3.62465 54.05735,-3.64296666666667
    54.0595333333333,-3.65568333333333 54.0740166666667,-3.6695 54.0932833333333,-3.65568333333333
    54.1054666666667,-3.63156666666667 54.1267166666667))
''')
print('\npoint within polygon?')
print(point.within(polygon))

# Geodataframe with 1 polygon
df = gpd.GeoDataFrame.from_dict({
    'id': [1],
    'geometry': [polygon],
})
# Geodataframe with 1 Point
poi = gpd.GeoDataFrame.from_dict({
    'id': [2],
    'geometry': [point],
})

print('\nSpatial join:')
print(gpd.sjoin(poi, df, predicate="within"))

```

#### Problem description

The spatial join behaviour (with GeoPandas PyGeos) has changed between Shapely 1.7.1 (correct behaviour) and Shapely 1.8 (incorrect behaviour).
Note that the point does not fall into the polygon. These are WGS84 coordinates, and the distance from the point to the polygon is ~400 meters.
![image](https://user-images.githubusercontent.com/20555592/139079313-9a65d086-642c-43b4-b6ae-b3c4655b271a.png)

**With Shapely 1.7.1 (correct behaviour)**
![image](https://user-images.githubusercontent.com/20555592/139079562-759234b4-30f4-4437-9abd-a497bed2a46b.png)

**With Shapely 1.8 (incorrect behaviour)**
Note that the point is still considered out of the polygon, but the spatial joins incorrectly considers the point to be in the polygon.
![image](https://user-images.githubusercontent.com/20555592/139079766-78658b65-8f16-431d-87d0-f2d45269156a.png)

#### Expected Output

The expected output is the one with Shapely 1.7.1. 
I think this comes from the fact that PyGeos & Shapely 1.8 are built on the same GEOS version, hence no conversions apply (the warnings does not appear). Maybe the formats are not exactly compatible. 

Indeed, the problem disappears if I force Pygeos to perform the WKB conversion between Shapely & Pygeos geometries.
More precisely, if I set the boolean shapely_compatible to False directly in Pygeos source code, I get the expected behaviour.
https://github.com/pygeos/pygeos/blob/41a48cfde8a0823c7ac44e4dc9b2cf6ae63f0f07/pygeos/io.py#L69

More details on the relative issue on GeoPandas: https://github.com/geopandas/geopandas/issues/2198

Note: the problem does not happen with pygeos 0.11.1, that is built on newer version of GEOS, but may happen again in the future if Shapely GEOS version is upgraded.

#### Output of ``geopandas.show_versions()``

This is the output with shapely 1.8.0. Simply run `pip install shapely==1.7.1` to test the working configuration.

<details>

SYSTEM INFO
-----------
python     : 3.9.5 (default, May  4 2021, 03:33:11)  [Clang 12.0.0 (clang-1200.0.32.29)]
executable : /Users/nicolaslegrand/.virtualenvs/py39/bin/python
machine    : macOS-10.16-x86_64-i386-64bit

GEOS, GDAL, PROJ INFO
---------------------
GEOS       : 3.9.1
GEOS lib   : /usr/local/Cellar/geos/3.9.1/lib/libgeos_c.dylib
GDAL       : 3.2.2
GDAL data dir: None
PROJ       : 7.2.1
PROJ data dir: /Users/nicolaslegrand/.virtualenvs/py39/lib/python3.9/site-packages/pyproj/proj_dir/share/proj

PYTHON DEPENDENCIES
-------------------
geopandas  : 0.10.2
pandas     : 1.2.5
fiona      : 1.8.19
numpy      : 1.21.3
shapely    : 1.8.0
rtree      : None
pyproj     : 3.0.1
matplotlib : 3.4.3
mapclassify: None
geopy      : 2.2.0
psycopg2   : 2.9.1 (dt dec pq3 ext lo64)
geoalchemy2: None
pyarrow    : None
pygeos     : 0.10.2

</details>

**Comment by caspervdw** [comment]
Thanks for the report! This looks bad… it seems that we just can’t shortcut the conversion between shapely and pygeos, even if GEOS versions are exactly the same (current behaviour).

Good news is that we plan to integrate the two projects. So conversion will be obsolete soon. In the meantime I the problem is fixed due to different versions of GEOS in the latest shapely and pygeos distributions. Any thoughts @jorisvandenbossche ?

**Comment by jorisvandenbossche** [comment]
Yeah, indeed the condition of "the same version" is apparently not always enough. On the geopandas issue I suggested that we could special case conda packages because we know in that case that it also uses exactly the same library:

> Maybe we should only set `shapely_compatible` to True if using conda, since with pip install you are never going to have the exact same GEOS library (except if you install both pygeos and shapely with pip from source with `--no-binary`)

I don't know what a generally robust way would be to detect the exact library that is being used by shapely and pygeos, so we can only use the fastpath when the library is identical (and not only same version). 
But I think we could at least detect that both shapely and pygeos are a conda package, in which case we know for sure they are using the same GEOS library.

**Comment by johnflavin** [comment]
Ignorant question: Is there a way to detect the actual library file(s) being used to load GEOS by shapely and pygeos? If you’re using wheels those files would be different even if their versions are the same, whereas installing with conda or a system GEOS there should only be one.

**Comment by caspervdw** [comment]
Indeed, that does not seem to be possible for pygeos. For pygeos the GEOS library is found by the dynamic linker, which (as far as I know) happens outside of the scope of the Python interpreter.

Maybe we can take a “duck-typing” approach. Then we need a reliable way of testing whether the geometries come through correctly.

**Comment by jorisvandenbossche** [comment]
I am also not aware of a way to easily "know" this in runtime (Shapely has some utilities to search the library in `shapely._buildcfg`, but you are still not guaranteed this actually corresponds with what is used by the compiled C code).

> I don’t think that there exists a generally robust way of exchanging opaque pointers through the python interpreter from one library to another anyway… the robust approach would be forcing wkb always. 

Yes, agreed, we should only do this for objects from the same library. And since this is hard to detect, forcing through WKB is indeed the safest option.

It's not super important at the moment, as you mention with the latest wheels you don't have the issue, but I would still like to keep the fastpath for people using pygeos with geopandas _when using conda_. If we have a way to detect that both shapely and pygeos are installed by conda, I think we can be sure they are using the same GEOS library. 

(anyway, another reason to move forward with merging shapely and pygeos :))
